name: Publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image with "latest" tag
        run: |
          nix build .#runrs-docker-image
          docker load < result
          docker push ${{ env.REGISTRY }}/bmc-labs/runrs:latest
      - name: Build and push Docker image with version tag
        run: |
          echo $(git describe --tags --always | tr --delete 'v' > version) && git add version
          nix build .#runrs-docker-image
          docker load < result
          docker push ${{ env.REGISTRY }}/bmc-labs/runrs:$(cat version)
