name: Publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and load Docker image with "latest" tag
        run: nix build .#runrs-docker-image && docker load < result
      - name: Push Docker image with "latest" tag to ghcr.io
        run: docker push ${{ env.REGISTRY }}/bmc-labs/runrs:latest
      - name: Retrieve version tag and add to git
        run: echo $(git describe --tags --always | tr --delete 'v' > version) && git add version
      - name: Build and load Docker image with version tag
        run: nix build .#runrs-docker-image && docker load < result
      - name: Push Docker image with release tag to ghcr.io
        run: docker push ${{ env.REGISTRY }}/bmc-labs/runrs:$(cat version)

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Docker
        run: |
          export DOCKER_HOST="${{ secrets.DOCKER_HOST }}"
          export TOKEN_SECRET="${{ secrets.TOKEN_SECRET }}"
          docker compose -f compose-deploy.yml up -d
